import type {
  ComparisonMetricDefinition,
  ComparisonMetricKey,
  ComparisonMode,
} from "../types";

export const COMPARISON_METRIC_REGISTRY: ComparisonMetricDefinition[] = [
  {
    key: "asking_price",
    category: "basics",
    labelCs: "Nabídková cena",
    direction: "lower_better",
    priorityInModes: ["overview", "own_home", "financing"],
  },
  {
    key: "price_per_sqm",
    category: "basics",
    labelCs: "Cena za m²",
    direction: "lower_better",
    priorityInModes: ["overview", "own_home"],
  },
  {
    key: "usable_area",
    category: "basics",
    labelCs: "Užitná plocha",
    direction: "higher_better",
    priorityInModes: ["overview", "own_home"],
  },
  {
    key: "layout",
    category: "basics",
    labelCs: "Dispozice",
    direction: "neutral",
    priorityInModes: ["overview", "own_home"],
  },
  {
    key: "property_type",
    category: "basics",
    labelCs: "Typ nemovitosti",
    direction: "neutral",
    priorityInModes: ["overview"],
  },
  {
    key: "condition",
    category: "basics",
    labelCs: "Stav",
    direction: "neutral",
    priorityInModes: ["own_home", "investment"],
  },
  {
    key: "valuation_mid",
    category: "value",
    labelCs: "Odhad Majetio (střed)",
    direction: "neutral",
    priorityInModes: ["overview", "own_home"],
    expandable: true,
  },
  {
    key: "asking_vs_valuation_pct",
    category: "value",
    labelCs: "Cena vs odhad",
    direction: "lower_better",
    priorityInModes: ["overview", "own_home", "investment"],
  },
  {
    key: "valuation_confidence",
    category: "value",
    labelCs: "Spolehlivost odhadu",
    direction: "neutral",
    priorityInModes: ["overview", "own_home", "investment"],
    expandable: true,
  },
  {
    key: "max_offer",
    category: "value",
    labelCs: "Max. nabídková cena (model)",
    direction: "higher_better",
    priorityInModes: ["investment", "own_home", "overview"],
    expandable: true,
  },
  {
    key: "max_offer_gap",
    category: "value",
    labelCs: "Gap (asking − max nabídka)",
    direction: "lower_better",
    priorityInModes: ["investment", "own_home", "overview"],
    expandable: true,
  },
  {
    key: "gross_yield_pct",
    category: "investment",
    labelCs: "Hrubý výnos",
    direction: "higher_better",
    priorityInModes: ["investment", "overview"],
    expandable: true,
  },
  {
    key: "net_yield_pct",
    category: "investment",
    labelCs: "Čistý výnos",
    direction: "higher_better",
    priorityInModes: ["investment"],
    expandable: true,
  },
  {
    key: "irr_pct",
    category: "investment",
    labelCs: "IRR (orientační)",
    direction: "higher_better",
    priorityInModes: ["investment"],
    expandable: true,
  },
  {
    key: "cash_flow_monthly",
    category: "investment",
    labelCs: "Cash flow měsíčně",
    direction: "higher_better",
    priorityInModes: ["investment", "overview"],
  },
  {
    key: "estimated_rent_monthly",
    category: "investment",
    labelCs: "Odhad nájmu",
    direction: "higher_better",
    priorityInModes: ["investment"],
  },
  {
    key: "ltv_pct",
    category: "financing",
    labelCs: "LTV",
    direction: "lower_better",
    priorityInModes: ["financing", "own_home"],
  },
  {
    key: "equity_required",
    category: "financing",
    labelCs: "Vlastní zdroje",
    direction: "lower_better",
    priorityInModes: ["financing", "own_home"],
  },
  {
    key: "loan_principal",
    category: "financing",
    labelCs: "Výše úvěru",
    direction: "neutral",
    priorityInModes: ["financing"],
  },
  {
    key: "monthly_payment",
    category: "financing",
    labelCs: "Orientační splátka",
    direction: "lower_better",
    priorityInModes: ["financing", "own_home"],
    expandable: true,
  },
  {
    key: "financing_gap",
    category: "financing",
    labelCs: "Finanční gap (chybějící zdroje)",
    direction: "lower_better",
    priorityInModes: ["financing", "own_home"],
    expandable: true,
  },
  {
    key: "renovation_cost_low",
    category: "renovation",
    labelCs: "Rekonstrukce — low",
    direction: "lower_better",
    priorityInModes: ["investment", "own_home"],
  },
  {
    key: "renovation_cost_base",
    category: "renovation",
    labelCs: "Rekonstrukce — base",
    direction: "lower_better",
    priorityInModes: ["investment", "own_home"],
    expandable: true,
  },
  {
    key: "renovation_cost_high",
    category: "renovation",
    labelCs: "Rekonstrukce — high",
    direction: "lower_better",
    priorityInModes: ["investment"],
  },
  {
    key: "renovation_cost",
    category: "renovation",
    labelCs: "Rekonstrukce (základ)",
    direction: "lower_better",
    priorityInModes: ["overview"],
  },
  {
    key: "renovation_duration",
    category: "renovation",
    labelCs: "Doba rekonstrukce",
    direction: "lower_better",
    priorityInModes: ["investment", "own_home"],
  },
  {
    key: "renovation_arv",
    category: "renovation",
    labelCs: "ARV (hodnota po rekonstrukci)",
    direction: "higher_better",
    priorityInModes: ["investment"],
  },
  {
    key: "location_label",
    category: "location",
    labelCs: "Lokalita",
    direction: "neutral",
    priorityInModes: ["overview", "own_home"],
  },
  {
    key: "city",
    category: "location",
    labelCs: "Město",
    direction: "neutral",
    priorityInModes: ["overview"],
  },
  {
    key: "location_score",
    category: "location",
    labelCs: "Skóre lokality",
    direction: "higher_better",
    priorityInModes: ["overview", "own_home", "investment"],
  },
  {
    key: "location_score_confidence",
    category: "location",
    labelCs: "Spolehlivost skóre lokality",
    direction: "neutral",
    priorityInModes: ["overview", "own_home"],
    expandable: true,
  },
  {
    key: "risk_critical",
    category: "risks",
    labelCs: "Rizika — kritická",
    direction: "lower_better",
    priorityInModes: ["overview", "investment", "own_home"],
  },
  {
    key: "risk_high",
    category: "risks",
    labelCs: "Rizika — vysoká",
    direction: "lower_better",
    priorityInModes: ["overview", "investment", "own_home"],
  },
  {
    key: "risk_medium",
    category: "risks",
    labelCs: "Rizika — střední",
    direction: "lower_better",
    priorityInModes: ["overview", "investment"],
  },
  {
    key: "risk_level",
    category: "risks",
    labelCs: "Celkové riziko",
    direction: "lower_better",
    priorityInModes: ["overview"],
  },
  {
    key: "majetio_score",
    category: "risks",
    labelCs: "Majetio skóre",
    direction: "higher_better",
    priorityInModes: ["overview", "investment"],
  },
  {
    key: "majetio_score_confidence",
    category: "risks",
    labelCs: "Spolehlivost Majetio skóre",
    direction: "neutral",
    priorityInModes: ["overview", "investment"],
    expandable: true,
  },
  {
    key: "match_score",
    category: "match",
    labelCs: "Shoda s profilem",
    direction: "higher_better",
    priorityInModes: ["own_home", "overview", "investment"],
  },
  {
    key: "match_score_confidence",
    category: "match",
    labelCs: "Spolehlivost shody",
    direction: "neutral",
    priorityInModes: ["own_home", "overview"],
    expandable: true,
  },
];

export function metricsForMode(mode: ComparisonMode): ComparisonMetricKey[] {
  const prioritized = COMPARISON_METRIC_REGISTRY.filter((m) =>
    m.priorityInModes.includes(mode),
  ).map((m) => m.key);
  const rest = COMPARISON_METRIC_REGISTRY.filter(
    (m) => !m.priorityInModes.includes(mode),
  ).map((m) => m.key);
  return [...prioritized, ...rest];
}

export function getMetricDefinition(
  key: ComparisonMetricKey,
): ComparisonMetricDefinition | undefined {
  return COMPARISON_METRIC_REGISTRY.find((m) => m.key === key);
}
