/**
 * Model demo floor plan for catalog ukazka-1 (2+kk · 54 m²).
 * Explicitly MODEL_DEMO — not reconstructed from illustration photos.
 */

import { disclaimerForKind, type FloorPlanDocument } from "./types";
import { rectPolygon } from "./geometry";

export const DEMO_2KK_FLOOR_PLAN: FloorPlanDocument = {
  schemaVersion: 1,
  outputKind: "MODEL_DEMO",
  scaleState: "FULL",
  units: "m",
  floors: [
    {
      id: "floor-0",
      name: "1. NP",
      level: 0,
      rooms: [
        {
          id: "room-hall",
          name: "Předsíň",
          type: "hallway",
          floorId: "floor-0",
          polygon: rectPolygon(0, 2.2, 1.4, 2.8),
          rotationDeg: 0,
          lengthM: 2.8,
          widthM: 1.4,
          areaM2: 3.9,
          areaSource: "model_demo",
          wallLengthsM: null,
          openings: [
            {
              id: "op-entry",
              kind: "door",
              edgeIndex: 3,
              t: 0.5,
              widthM: 0.9,
              swing: "in_right",
              connectsToRoomId: null,
            },
            {
              id: "op-hall-living",
              kind: "passage",
              edgeIndex: 1,
              t: 0.55,
              widthM: 0.9,
              connectsToRoomId: "room-living",
            },
            {
              id: "op-hall-bath",
              kind: "door",
              edgeIndex: 0,
              t: 0.4,
              widthM: 0.7,
              swing: "in_left",
              connectsToRoomId: "room-bath",
            },
          ],
          notes: "Modelová dispozice",
          unclear: false,
          photoGroupIds: [],
        },
        {
          id: "room-living",
          name: "Obývací pokoj s kuchyní",
          type: "living",
          floorId: "floor-0",
          polygon: rectPolygon(1.4, 0, 5.2, 5.0),
          rotationDeg: 0,
          lengthM: 5.2,
          widthM: 5.0,
          areaM2: 26.0,
          areaSource: "model_demo",
          wallLengthsM: null,
          openings: [
            {
              id: "op-living-win",
              kind: "window",
              edgeIndex: 1,
              t: 0.45,
              widthM: 1.8,
            },
            {
              id: "op-living-bed",
              kind: "door",
              edgeIndex: 0,
              t: 0.7,
              widthM: 0.8,
              swing: "in_left",
              connectsToRoomId: "room-bed",
            },
          ],
          notes: null,
          unclear: false,
          photoGroupIds: [],
        },
        {
          id: "room-bed",
          name: "Ložnice",
          type: "bedroom",
          floorId: "floor-0",
          polygon: rectPolygon(1.4, 5.0, 3.6, 3.5),
          rotationDeg: 0,
          lengthM: 3.6,
          widthM: 3.5,
          areaM2: 12.6,
          areaSource: "model_demo",
          wallLengthsM: null,
          openings: [
            {
              id: "op-bed-win",
              kind: "window",
              edgeIndex: 2,
              t: 0.5,
              widthM: 1.4,
            },
          ],
          notes: null,
          unclear: false,
          photoGroupIds: [],
        },
        {
          id: "room-bath",
          name: "Koupelna",
          type: "bathroom",
          floorId: "floor-0",
          polygon: rectPolygon(0, 0, 1.4, 2.2),
          rotationDeg: 0,
          lengthM: 2.2,
          widthM: 1.4,
          areaM2: 3.1,
          areaSource: "model_demo",
          wallLengthsM: null,
          openings: [],
          notes: null,
          unclear: false,
          photoGroupIds: [],
        },
        {
          id: "room-balcony",
          name: "Balkon",
          type: "balcony",
          floorId: "floor-0",
          polygon: rectPolygon(6.6, 1.5, 1.2, 2.5),
          rotationDeg: 0,
          lengthM: 2.5,
          widthM: 1.2,
          areaM2: 3.0,
          areaSource: "model_demo",
          wallLengthsM: null,
          openings: [
            {
              id: "op-balc",
              kind: "door",
              edgeIndex: 3,
              t: 0.5,
              widthM: 0.9,
              swing: "out_right",
              connectsToRoomId: "room-living",
            },
          ],
          notes: "Balkon mimo užitnou plochu bytu v některých výpočtech",
          unclear: false,
          photoGroupIds: [],
        },
      ],
    },
  ],
  photoGroups: [],
  sourceFiles: [],
  showFurniture: false,
  issues: [
    {
      code: "model_demo",
      messageCs:
        "Modelová dispozice 2+kk. Neodvozuje se z ilustračních fotografií inzerátu.",
      severity: "info",
    },
  ],
  listedAreaM2: 54,
  roomsAreaSumM2: 48.6,
  areaDifferenceNoteCs:
    "Součet místností 48,6 m² + balkon 3 m². Inzertní 54 m² může zahrnovat příčky a zaokrouhlení — ověřte výměru.",
  disclaimerCs: disclaimerForKind("MODEL_DEMO"),
};
