import type { MarketPlugin } from "@/domains/markets/plugins/types";

export const itMarketPlugin: MarketPlugin = {
  marketCode: "IT",
  definition: {
    marketCode: "IT",
    countryCode: "IT",
    displayNameEn: "Italy",
    displayNameLocal: "Italia",
    defaultLocale: "it-IT",
    supportedLocales: ["it-IT", "en-GB"],
    defaultCurrency: "EUR",
    timezone: "Europe/Rome",
    measurementSystem: "METRIC",
    enabled: false,
    launchStatus: "PLANNED",
    regulatoryConfigVersion: "it-reg.planned",
    hasMinimumPublicData: false,
  },
  property: {
    areaUnit: "sqm",
    supportedPropertyTypes: ["APARTMENT", "HOUSE", "LAND", "OTHER"],
    addressModel: "EU_STREET",
    titleDeedLabelEn: "Visura catastale / Conservatoria",
    layoutNotation: "BEDROOM_COUNT",
    detailSectionExtraIds: [],
    searchFilterExtraKeys: ["bedrooms", "bathrooms"],
  },
  transactionCosts: {
    packId: "it-tx-costs.planned",
    buyerClosingCostBpsEstimate: 900,
    sellerClosingCostBpsEstimate: 400,
    transferTaxLabelEn: "Imposta di registro / IVA (illustrative)",
    notesEn: "Notary-heavy closing — pack required.",
  },
  financing: {
    mortgageAvailable: true,
    partnerHandoffEnabled: false,
    typicalLtvMaxPct: 80,
    rateBenchmarkLabelEn: null,
    currency: "EUR",
    primaryProviderCode: null,
  },
  taxation: {
    standardVatRateBp: 2200,
    propertyTaxModel: "ANNUAL",
    rentalIncomeTaxNotesEn: "IMU / cedolare secca — pending pack.",
    regulatoryPackId: "it-tax.planned",
    taxPluginId: null,
  },
  regulatory: {
    rulesVersion: "it-reg.planned",
    renovationCatalogAvailable: false,
    valuationModelCodes: [],
  },
  capabilities: {
    PROPERTY_SEARCH: "NOT_AVAILABLE",
    VALUATION: "NOT_AVAILABLE",
    INVESTMENT_ENGINE: "NOT_AVAILABLE",
    MORTGAGE_CALCULATOR: "NOT_AVAILABLE",
    MORTGAGE_LEAD_HANDOFF: "NOT_AVAILABLE",
    COMPARISON: "NOT_AVAILABLE",
    LOCATION_INTELLIGENCE: "NOT_AVAILABLE",
    LISTING_BOOST: "NOT_AVAILABLE",
    B2B_CRM: "NOT_AVAILABLE",
    QUALIFIED_LEADS: "NOT_AVAILABLE",
    TAX_ESTIMATES: "NOT_AVAILABLE",
    TRANSACTION_COST_ESTIMATES: "NOT_AVAILABLE",
    PROFESSIONAL_SERVICES: "NOT_AVAILABLE",
  },
  featureFlagDefaults: {
    MARKET_IT_VALUATION_ENABLED: false,
  },
};
