export const INVESTMENT_ENGINE_VERSION = "0.4.0-risk";

export {
  moneyMinorDtoSchema,
  moneyMinorDtoOrNullSchema,
  moneyMajorDtoSchema,
  moneyToDto,
  moneyFromDto,
  moneyFromDtoOrNull,
  moneyFromMajorDto,
  type MoneyMinorDto,
  type MoneyMajorDto,
  type CurrencyCode,
} from "./money";

export {
  percentageRatioDtoSchema,
  percentageRatioDtoOrNullSchema,
  percentageToDto,
  percentageFromDto,
  percentageFromDtoOrNull,
  percentPointsInputSchema,
  type PercentageRatioDto,
} from "./percentage";

export {
  ROUNDING_POLICY,
  DECIMAL_CONFIG,
  roundInternal,
  roundMoneyMajorForDisplay,
  roundPercentPointsForDisplay,
  roundRatePercentPointsForDisplay,
  roundMoneyForUi,
  roundMoneyDtoForUi,
  percentPointsForUi,
  percentageDtoForUi,
  describeRoundingPolicy,
  toDecimal,
} from "./rounding";

export {
  acquisitionCostLineKeys,
  totalAcquisitionCostInputSchema,
  parseTotalAcquisitionCostInput,
  toAcquisitionCostBreakdown,
  computeTotalAcquisitionCost,
  totalAcquisitionCostToDto,
  type AcquisitionCostLineKey,
  type TotalAcquisitionCostInput,
  type TotalAcquisitionCostBreakdown,
  type TotalAcquisitionCost,
} from "./acquisition-cost";

export {
  FORMULA_REGISTRY,
  FORMULA_REGISTRY_VERSION,
  getFormula,
  requireFormula,
  listFormulaKeys,
  type FormulaDefinition,
  type FormulaKey,
} from "./formulas/registry";

export {
  investmentCalculationInputSchema,
  parseInvestmentCalculationInput,
  safeParseInvestmentCalculationInput,
  financingInputSchema,
  incomeExpenseInputSchema,
  marketAssumptionsInputSchema,
  propertyContextInputSchema,
  investmentHorizonSchema,
  type InvestmentCalculationInput,
} from "./schemas/input";

export {
  investmentCalculationResultSchema,
  parseInvestmentCalculationResult,
  safeParseInvestmentCalculationResult,
  calculationMetricSchema,
  moneyMetricSchema,
  ratioMetricSchema,
  totalAcquisitionCostResultSchema,
  insufficientMoneyMetric,
  insufficientRatioMetric,
  type InvestmentCalculationResult,
  type CalculationMetric,
} from "./schemas/result";

export {
  bindFormula,
  moneyOverMoney,
  annualFromMonthly,
  monthlyFromAnnual,
  calculateAnnuityPayment,
  calculateDscr,
  annualDebtServiceFromMonthly,
  calculateGrossIncome,
  calculateAnnualOperatingExpenses,
  calculateNoi,
  calculateYields,
  calculateCapRate,
  calculateCashFlows,
  calculateEquityRequired,
  calculateLtv,
  calculateCashOnCash,
  buildAmortizationSchedule,
  outstandingLoanBalance,
  growMoneyAnnual,
  calculateNetSaleProceeds,
  projectSalePrice,
  projectHoldingPeriod,
  calculateIrr,
  calculateEquityMultiple,
  calculatePaybackPeriod,
  buildEquityCashFlowSeries,
  countCashFlowSignChanges,
  calculateNpv,
  type FormulaBound,
  type AnnuityPaymentInput,
  type AnnuityPaymentResult,
  type DscrInput,
  type DscrResult,
  type GrossIncomeInput,
  type GrossIncomeResult,
  type OperatingExpenseLines,
  type OperatingExpensesResult,
  type NoiInput,
  type NoiResult,
  type YieldInput,
  type YieldResult,
  type CapRateInput,
  type CashFlowInput,
  type CashFlowResult,
  type EquityRequiredInput,
  type LtvInput,
  type CashOnCashInput,
  type AmortizationRow,
  type AmortizationScheduleInput,
  type AmortizationScheduleResult,
  type NetSaleProceedsInput,
  type NetSaleProceedsResult,
  type HoldingProjectionInput,
  type HoldingYearRow,
  type HoldingProjectionResult,
  type EquityCashFlowSeries,
  type IrrResult,
  type EquityMultipleResult,
  type PaybackResult,
  type NpvInput,
  type NpvResult,
} from "./calculations";

export {
  SCENARIO_KINDS,
  calculateLongTermRentalScenario,
  calculateCashPurchaseScenario,
  calculateSeasonalGrossIncome,
  calculateShortTermRentalScenario,
  calculateFlipScenario,
  calculateRenovationRentScenario,
  type ScenarioKind,
  type ScenarioGrowthAssumptions,
  type ScenarioLoanAssumptions,
  type LongTermRentalScenarioInput,
  type CashPurchaseScenarioInput,
  type SeasonalMonthInput,
  type ShortTermRentalScenarioInput,
  type FlipScenarioInput,
  type RenovationRentScenarioInput,
  type AnyScenarioResult,
} from "./scenarios";

export {
  evaluateYear1Metrics,
  shiftNominalRateByPercentagePoints,
  DEFAULT_CANONICAL_SPREADS,
  deriveCanonicalScenarios,
  runOneWaySensitivity,
  runTwoWaySensitivity,
  calculateBreakEvenOccupancy,
  calculateBreakEvenInterestRate,
  calculateBreakEvenPurchasePrice,
  STRESS_SHOCK_IDS,
  runStressTests,
  RISK_FLAG_CODES,
  DEFAULT_RISK_THRESHOLDS,
  evaluateRiskFlags,
  INPUT_PROVENANCE_KINDS,
  PROVENANCE_QUALITY,
  calculateConfidenceScore,
  type RiskBaseCase,
  type Year1OperatingMetrics,
  type CanonicalSpreads,
  type CanonicalScenarioLabel,
  type CanonicalTripletResult,
  type SensitivityFactor,
  type SensitivityMetricKey,
  type OneWaySensitivityResult,
  type TwoWaySensitivityResult,
  type BreakEvenOccupancyResult,
  type BreakEvenInterestResult,
  type BreakEvenPurchasePriceResult,
  type StressShockId,
  type StressTestSuiteResult,
  type RiskFlagCode,
  type RiskFlag,
  type RiskFlagsResult,
  type RiskFlagThresholds,
  type InputProvenanceKind,
  type InputFieldProvenance,
  type ConfidenceScoreResult,
} from "./risk";

export {
  CALCULATION_ERROR_CATEGORIES,
  RESULT_WARNING_CODES,
  calculationIntentSchema,
  validateDomainInputs,
  classifyLoanAmount,
  notApplicableMoneyMetric,
  notApplicableRatioMetric,
  errorMoneyMetric,
  errorRatioMetric,
  type CalculationErrorCategory,
  type CalculationIssue,
  type ResultWarning,
  type ResultWarningCode,
  type CalculationIntent,
} from "./validation";
