import type { MarketPlugin } from "@/domains/markets/plugins/types";

export const aeMarketPlugin: MarketPlugin = {
  marketCode: "AE",
  definition: {
    marketCode: "AE",
    countryCode: "AE",
    displayNameEn: "United Arab Emirates",
    displayNameLocal: "الإمارات",
    defaultLocale: "en-AE",
    supportedLocales: ["en-AE", "ar-AE"],
    defaultCurrency: "AED",
    timezone: "Asia/Dubai",
    measurementSystem: "METRIC",
    enabled: false,
    launchStatus: "RESEARCH",
    regulatoryConfigVersion: "ae-reg.research",
    hasMinimumPublicData: false,
    notesEn: "Freehold / leasehold complexity — emirate-level rules later.",
  },
  property: {
    areaUnit: "sqft",
    supportedPropertyTypes: [
      "APARTMENT",
      "HOUSE",
      "VILLA",
      "TOWNHOUSE",
      "STUDIO",
      "COMMERCIAL",
      "OTHER",
    ],
    addressModel: "GULF",
    titleDeedLabelEn: "Title deed / Oqood",
    layoutNotation: "BEDROOM_COUNT",
    detailSectionExtraIds: [
      "freehold",
      "service_charge",
      "payment_plan",
      "off_plan",
    ],
    searchFilterExtraKeys: [
      "bedrooms",
      "bathrooms",
      "freehold",
      "offPlan",
      "serviceChargeMax",
      "paymentPlan",
    ],
  },
  transactionCosts: {
    packId: "ae-tx-costs.v2026.07",
    buyerClosingCostBpsEstimate: 600,
    sellerClosingCostBpsEstimate: 200,
    transferTaxLabelEn: "DLD / transfer fee (illustrative)",
    notesEn: "Emirate-specific — Dubai vs Abu Dhabi packs TBD.",
  },
  financing: {
    mortgageAvailable: true,
    partnerHandoffEnabled: false,
    typicalLtvMaxPct: 80,
    rateBenchmarkLabelEn: null,
    currency: "AED",
    primaryProviderCode: "ae_partner_tbd",
  },
  taxation: {
    standardVatRateBp: 500,
    propertyTaxModel: "NONE",
    rentalIncomeTaxNotesEn: "No personal income tax today — verify pack.",
    regulatoryPackId: "ae-tax.research",
    taxPluginId: null,
  },
  regulatory: {
    rulesVersion: "ae-reg.v2026.07",
    renovationCatalogAvailable: false,
    valuationModelCodes: ["AE_APARTMENT_V1", "AE_VILLA_V1"],
  },
  capabilities: {
    PROPERTY_SEARCH: "NOT_AVAILABLE",
    VALUATION: "NOT_AVAILABLE",
    INVESTMENT_ENGINE: "NOT_AVAILABLE",
    MORTGAGE_CALCULATOR: "NOT_AVAILABLE",
    MORTGAGE_LEAD_HANDOFF: "NOT_AVAILABLE",
    COMPARISON: "NOT_AVAILABLE",
    LOCATION_INTELLIGENCE: "NOT_AVAILABLE",
    LISTING_BOOST: "NOT_AVAILABLE",
    B2B_CRM: "NOT_AVAILABLE",
    QUALIFIED_LEADS: "NOT_AVAILABLE",
    TAX_ESTIMATES: "NOT_AVAILABLE",
    TRANSACTION_COST_ESTIMATES: "MANUAL_ONLY",
    PROFESSIONAL_SERVICES: "NOT_AVAILABLE",
  },
  featureFlagDefaults: {
    MARKET_AE_VALUATION_ENABLED: false,
  },
};
