import type { HousingOptionCategory } from "./types";

const u = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=75`;

/** Mix interiérů, exteriérů, rekreačních a zahraničních scén — bez monotónních kopií. */
const IMG = {
  villa: "/home/prop-villa.png",
  town: "/home/prop-townhouse.png",
  hero: "/home/hero.png",
  rental: "/case-studies/rental-apartment.png",
  building: "/case-studies/small-building.png",
  invest: "/home/cat-invest.png",
  homeHero: "/case-studies/homepage-hero.png",
  aptBright: u("photo-1522708323590-d24dbb6b0267"),
  aptModern: u("photo-1502672260266-1c1ef2d93688"),
  aptLuxury: u("photo-1600596542815-ffad4c1539a9"),
  aptCozy: u("photo-1586023492125-27b2c045efd7"),
  aptStudio: u("photo-1493809842364-78817add7ffb"),
  houseExt: u("photo-1600585154340-be6161a56a0c"),
  houseFamily: u("photo-1600566753190-17f0baa2a6c3"),
  houseLarge: u("photo-1613490493576-7fde63acd811"),
  houseCountry: u("photo-1564013799919-ab600027ffc6"),
  skyline: u("photo-1486406146926-c627a92ad1ab"),
  townhouse: u("photo-1570129477492-45c003edd2be"),
  cabin: u("photo-1518780664697-55e3ab609ef9"),
  land: u("photo-1500382017468-9049fed747ef"),
  coast: u("photo-1499793983690-e29dafd12df4"),
  dubai: u("photo-1512453979798-5ea266f8880c"),
  italy: u("photo-1516483638261-f4dbaf036963"),
  bali: u("photo-1537996194471-e657df975ab4"),
  croatia: u("photo-1555881400-74d7acaacd8b"),
  farm: u("photo-1500076656116-5589c9489c7a"),
  seniorHome: u("photo-1484154218962-a197022b5858"),
  loft: u("photo-1560448204-e02f11c3d0e2"),
} as const;

export const HOUSING_OPTION_CATEGORIES: HousingOptionCategory[] = [
  {
    slug: "sdilena-investice",
    title: "Sdílená investice",
    seoTitle: "Sdílená investice do nemovitostí",
    seoDescription:
      "Modelové příklady společné investice do nemovitostí — podíly, vklady a orientační cashflow. Ilustrativní scénáře Majetio.",
    subtitle: "Investujte do nemovitosti společně s dalšími investory.",
    explanation:
      "Více investorů se podílí na financování a vlastnictví investice. Každý vkládá kapitál odpovídající dohodnutému podílu a podle modelu se podílí na výnosech i nákladech.",
    benefits: [
      { title: "Nižší vstupní kapitál", text: "Do prémiové lokality se dostanete s menším vkladem." },
      { title: "Sdílené riziko", text: "Riziko i výnos se rozdělí mezi více účastníků." },
      { title: "Orientační cashflow", text: "Model ukáže podíl na nájmu a hrubý výnos." },
      { title: "Transparentní podíly", text: "Procenta a vklady jsou předem srozumitelné." },
    ],
    steps: [
      { title: "Vyberte model", text: "Prohlédněte ukázkové scénáře podle lokality a kapitálu." },
      { title: "Porovnejte podíly", text: "Sledujte počet investorů, vklad a orientační výnos." },
      { title: "Dejte vědět zájem", text: "Zaznamenejte nezávazný zájem — bez převodu vlastnictví." },
    ],
    risks: [
      "Podíly a výnosy v modelech jsou ilustrativní, ne smluvní závazek.",
      "Sdílené vlastnictví vyžaduje právní a daňové nastavení mimo platformu.",
      "Cashflow závisí na obsazenosti, nákladech a dohodě mezi investory.",
    ],
    ctaLabel: "Mám o tuto možnost zájem",
    ctaHref: "#zajemn",
    interestMode: "SHARED_INVESTMENT",
    showSharePct: true,
    examples: [
      {
        id: "si-1",
        slug: "usti-garsonka",
        title: "Levnější investiční garsonka",
        location: "Ústí nad Labem – centrum",
        propertyType: "Garsonka · 1+kk",
        priceLabel: "2 400 000 Kč",
        image: IMG.aptStudio,
        gallery: [IMG.aptStudio, IMG.aptCozy],
        description:
          "Vstupní scénář pro dva investory — nízký kapitál, vyšší modelový výnos v regionu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Cena nemovitosti", value: "2 400 000 Kč", emphasize: true },
          { label: "Počet investorů", value: "2" },
          { label: "Podíl na osobu", value: "50 %" },
          { label: "Vklad jednoho investora", value: "1 200 000 Kč" },
          { label: "Odhad nájmu", value: "11 500 Kč / měs." },
          { label: "Podíl nájmu / osoba", value: "5 750 Kč / měs." },
          { label: "Orientační hrubý výnos", value: "5,8 %" },
        ],
        scenario: "Vhodné pro první společnou investici s omezeným kapitálem.",
        howItWorks: [
          "Dva investoři deklarují podíl 50/50.",
          "Nájem z dlouhodobého pronájmu se dělí napůl po nákladech.",
          "Model neřeší správu — tu domluvíte mimo platformu.",
        ],
      },
      {
        id: "si-2",
        slug: "praha-vinohrady",
        title: "Dražší městský byt Praha",
        location: "Praha 2 – Vinohrady",
        propertyType: "Byt 3+kk · prémiový",
        priceLabel: "11 200 000 Kč",
        image: IMG.aptLuxury,
        gallery: [IMG.aptLuxury, IMG.aptModern, IMG.loft],
        description:
          "Pět investorů po 20 % v prémiové lokalitě — nižší výnos, silnější adresa.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Cena nemovitosti", value: "11 200 000 Kč", emphasize: true },
          { label: "Počet investorů", value: "5" },
          { label: "Podíl na osobu", value: "20 %" },
          { label: "Vklad jednoho investora", value: "2 240 000 Kč" },
          { label: "Odhad nájmu", value: "38 000 Kč / měs." },
          { label: "Podíl nájmu / osoba", value: "7 600 Kč / měs." },
          { label: "Orientační hrubý výnos", value: "4,1 %" },
        ],
        scenario: "Pro investory, kteří preferují stabilní lokalitu před maximálním výnosem.",
      },
      {
        id: "si-3",
        slug: "brno-dum",
        title: "Rodinný dům Brno",
        location: "Brno – Židenice",
        propertyType: "Rodinný dům",
        priceLabel: "8 500 000 Kč",
        image: IMG.houseFamily,
        gallery: [IMG.houseFamily, IMG.houseExt],
        description: "Tři investoři — dlouhodobý pronájem rodiny nebo více generací.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Cena nemovitosti", value: "8 500 000 Kč", emphasize: true },
          { label: "Počet investorů", value: "3" },
          { label: "Podíl na osobu", value: "33,3 %" },
          { label: "Vklad jednoho investora", value: "cca 2 833 000 Kč" },
          { label: "Odhad nájmu", value: "32 000 Kč / měs." },
          { label: "Podíl nájmu / osoba", value: "cca 10 700 Kč / měs." },
          { label: "Orientační hrubý výnos", value: "4,5 %" },
        ],
      },
      {
        id: "si-4",
        slug: "krkonose-apartman",
        title: "Rekreační apartmán Krkonoše",
        location: "Špindlerův Mlýn",
        propertyType: "Apartmán · short-term",
        priceLabel: "7 200 000 Kč",
        image: IMG.cabin,
        gallery: [IMG.cabin, IMG.coast],
        description: "Sezónní short-term model — vyšší výkyvy než městský nájem.",
        badge: "Ukázková nabídka",
        metrics: [
          { label: "Cena nemovitosti", value: "7 200 000 Kč", emphasize: true },
          { label: "Počet investorů", value: "4" },
          { label: "Podíl na osobu", value: "25 %" },
          { label: "Vklad jednoho investora", value: "1 800 000 Kč" },
          { label: "Odhad výnosu sezóny", value: "28 000 Kč / měs. prům." },
          { label: "Podíl / osoba", value: "7 000 Kč / měs." },
          { label: "Orientační hrubý výnos", value: "4,7 %" },
        ],
      },
      {
        id: "si-5",
        slug: "ostrava-dum",
        title: "Menší bytový dům Ostrava",
        location: "Ostrava – Poruba",
        propertyType: "Bytový dům · 4 jednotky",
        priceLabel: "14 000 000 Kč",
        image: IMG.skyline,
        gallery: [IMG.skyline, IMG.townhouse, IMG.building],
        description: "Pět investorů po 20 % — cashflow z více bytů v jednom objektu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Cena nemovitosti", value: "14 000 000 Kč", emphasize: true },
          { label: "Počet investorů", value: "5" },
          { label: "Podíl na osobu", value: "20 %" },
          { label: "Vklad jednoho investora", value: "2 800 000 Kč" },
          { label: "Odhad nájmu", value: "78 000 Kč / měs." },
          { label: "Podíl nájmu / osoba", value: "15 600 Kč / měs." },
          { label: "Orientační hrubý výnos", value: "6,7 %" },
        ],
      },
    ],
  },
  {
    slug: "castecna-koupe",
    title: "Částečná koupě",
    seoTitle: "Částečná koupě nemovitosti",
    seoDescription:
      "Modelové příklady koupě podílu s možností pozdějšího odkupu. Ilustrativní scénáře Majetio.",
    subtitle: "Kupte část nemovitosti a zbytek můžete postupně odkoupit.",
    explanation:
      "Klient koupí pouze část nemovitosti. Zbývající podíl zůstává u druhého vlastníka nebo partnera a lze jej podle dohody postupně odkoupit.",
    benefits: [
      { title: "Nižší vstup", text: "Začnete s menším kapitálem než při plné koupi." },
      { title: "Cesta k 100 %", text: "Modelový plán ukazuje postupný odkup." },
      { title: "Flexibilita", text: "Podíl dnes, zbytek podle vašich možností." },
      { title: "Jasná čísla", text: "Hodnota, podíl a kapitál na první pohled." },
    ],
    steps: [
      { title: "Zvolte podíl", text: "Podívejte se na modelové procento vlastnictví." },
      { title: "Spočítejte kapitál", text: "Počáteční vklad = podíl × hodnota." },
      { title: "Naplánujte odkup", text: "Zvažte modelový plán budoucího doplatku." },
    ],
    risks: [
      "Postupný odkup musí být právně ošetřen — model není smlouva.",
      "Hypotéka na podíl nemusí být standardně dostupná.",
      "Cena zbývajícího podílu se může v čase měnit.",
    ],
    ctaLabel: "Mám o tuto možnost zájem",
    ctaHref: "#zajemn",
    interestMode: "PARTIAL_BUY",
    showSharePct: true,
    examples: [
      {
        id: "ck-1",
        slug: "ostrava-25",
        title: "Novostavba — podíl 25 %",
        location: "Ostrava – Centrum",
        propertyType: "Byt · novostavba 2+kk",
        priceLabel: "Hodnota 6 700 000 Kč",
        image: IMG.aptModern,
        gallery: [IMG.aptModern, IMG.skyline],
        description: "Nejnižší vstupní podíl — delší modelový plán odkupu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Celková hodnota", value: "6 700 000 Kč", emphasize: true },
          { label: "Kupovaný podíl", value: "25 %" },
          { label: "Počáteční kapitál", value: "1 675 000 Kč" },
          { label: "Podíl k odkupu", value: "75 %" },
          { label: "Modelový plán odkupu", value: "10× 502 500 Kč" },
          { label: "Cílový uživatel", value: "Young buyer · nízký vstup" },
        ],
      },
      {
        id: "ck-2",
        slug: "pardubice-30",
        title: "Investiční byt — podíl 30 %",
        location: "Pardubice – Polabiny",
        propertyType: "Byt 1+1 · investiční",
        priceLabel: "Hodnota 3 100 000 Kč",
        image: IMG.aptBright,
        gallery: [IMG.aptBright, IMG.aptStudio],
        description: "Menší investiční jednotka — 30 % dnes, zbytek k odkupu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Celková hodnota", value: "3 100 000 Kč", emphasize: true },
          { label: "Kupovaný podíl", value: "30 %" },
          { label: "Počáteční kapitál", value: "930 000 Kč" },
          { label: "Podíl k odkupu", value: "70 %" },
          { label: "Modelový plán odkupu", value: "7× 310 000 Kč" },
          { label: "Cílový uživatel", value: "Investor s malým kapitálem" },
        ],
      },
      {
        id: "ck-3",
        slug: "plzen-40",
        title: "Rodinný dům — podíl 40 %",
        location: "Plzeň – Lochotín",
        propertyType: "Rodinný dům",
        priceLabel: "Hodnota 8 000 000 Kč",
        image: IMG.houseExt,
        gallery: [IMG.houseExt, IMG.houseFamily],
        description: "Čtyřicetiprocentní podíl na klasickém rodinném bydlení.",
        badge: "Ukázková nabídka",
        metrics: [
          { label: "Celková hodnota", value: "8 000 000 Kč", emphasize: true },
          { label: "Kupovaný podíl", value: "40 %" },
          { label: "Počáteční kapitál", value: "3 200 000 Kč" },
          { label: "Podíl k odkupu", value: "60 %" },
          { label: "Modelový plán odkupu", value: "6× 800 000 Kč" },
          { label: "Cílový uživatel", value: "Rodina · postupný odkup" },
        ],
      },
      {
        id: "ck-4",
        slug: "praha-50",
        title: "Městský byt Praha — podíl 50 %",
        location: "Praha 4 – Pankrác",
        propertyType: "Byt 2+kk · městský",
        priceLabel: "Hodnota 6 000 000 Kč",
        image: IMG.loft,
        gallery: [IMG.loft, IMG.aptCozy],
        description: "Poloviční podíl v Praze — vyvážený vstup a tempo odkupu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Celková hodnota", value: "6 000 000 Kč", emphasize: true },
          { label: "Kupovaný podíl", value: "50 %" },
          { label: "Počáteční kapitál", value: "3 000 000 Kč" },
          { label: "Podíl k odkupu", value: "50 %" },
          { label: "Modelový plán odkupu", value: "5× 600 000 Kč / rok" },
          { label: "Cílový uživatel", value: "Pár · bydlení + odkup" },
        ],
        scenario: "Po pěti stejných splátkách modelu dosáhnete 100 % vlastnictví.",
      },
      {
        id: "ck-5",
        slug: "stredocesky-60",
        title: "Větší rodinné bydlení — podíl 60 %",
        location: "Středočeský kraj – Průhonice",
        propertyType: "Vila · 5+kk",
        priceLabel: "Hodnota 14 500 000 Kč",
        image: IMG.houseLarge,
        gallery: [IMG.houseLarge, IMG.houseCountry],
        description: "Majorita 60 % u většího rodinného bydlení — vyšší kapitál, kratší odkup.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Celková hodnota", value: "14 500 000 Kč", emphasize: true },
          { label: "Kupovaný podíl", value: "60 %" },
          { label: "Počáteční kapitál", value: "8 700 000 Kč" },
          { label: "Podíl k odkupu", value: "40 %" },
          { label: "Modelový plán odkupu", value: "4× 1 450 000 Kč" },
          { label: "Cílový uživatel", value: "Rodina · větší bydlení" },
        ],
      },
    ],
  },
  {
    slug: "sdileny-najem",
    title: "Sdílený nájem",
    seoTitle: "Sdílený nájem",
    seoDescription:
      "Modelové příklady společného nájmu větší nemovitosti — cena na osobu, kauce a vybavení.",
    subtitle: "Více lidí společně pronajímá větší nemovitost.",
    explanation:
      "Sdílený nájem spojuje rozpočty několika osob. Celkový nájem se dělí podle dohody — typicky rovnoměrně, případně podle velikosti pokojů.",
    benefits: [
      { title: "Nižší náklady", text: "Cena na osobu je výrazně nižší než u samostatného bytu." },
      { title: "Větší prostor", text: "Společně dosáhnete na větší dispozici." },
      { title: "Flexibilita", text: "Počet míst a rozpočet lze modelovat dopředu." },
      { title: "Jasné metriky", text: "Nájem, kauce i energie na první pohled." },
    ],
    steps: [
      { title: "Zvolte kapacitu", text: "Kolik osob a jaká dispozice dává smysl." },
      { title: "Spočítejte podíl", text: "Celkový nájem ÷ počet osob." },
      { title: "Domluvte podmínky", text: "Kauce, energie a pravidla spolubydlení." },
    ],
    risks: [
      "Solidární odpovědnost za nájem závisí na smlouvě.",
      "Změna spolubydlícího může vyžadovat souhlas majitele.",
      "Energie a služby mohou být vyšší, než očekáváte.",
    ],
    ctaLabel: "Najít podobné nabídky",
    ctaHref: "/nemovitosti?nabidka=pronajem",
    interestMode: "SHARED_RENT",
    examples: [
      {
        id: "sn-1",
        slug: "brno-studenti",
        title: "Studentský byt Brno",
        location: "Brno – Veveří",
        propertyType: "Byt 3+1 · studentský",
        priceLabel: "6 500 Kč / osoba",
        image: IMG.aptStudio,
        gallery: [IMG.aptStudio, IMG.aptBright],
        description: "Tři studenti, základní vybavení, nízká cena na osobu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Dispozice", value: "3+1" },
          { label: "Počet míst", value: "3" },
          { label: "Nájem celkem", value: "19 500 Kč", emphasize: true },
          { label: "Cena / osoba", value: "6 500 Kč" },
          { label: "Kauce", value: "19 500 Kč" },
          { label: "Energie orientačně", value: "2 400 Kč / měs." },
          { label: "Vybavení", value: "Základní" },
          { label: "Cílová skupina", value: "Studenti" },
        ],
      },
      {
        id: "sn-2",
        slug: "praha-professionals",
        title: "Young professionals Praha",
        location: "Praha 7 – Holešovice",
        propertyType: "Byt 3+kk · equipped",
        priceLabel: "12 500 Kč / osoba",
        image: IMG.aptModern,
        gallery: [IMG.aptModern, IMG.loft],
        description: "Tři mladí profesionálové — plně vybaveno, vyšší standard.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Dispozice", value: "3+kk" },
          { label: "Počet míst", value: "3" },
          { label: "Nájem celkem", value: "37 500 Kč", emphasize: true },
          { label: "Cena / osoba", value: "12 500 Kč" },
          { label: "Kauce", value: "37 500 Kč" },
          { label: "Energie orientačně", value: "4 200 Kč / měs." },
          { label: "Vybavení", value: "Kompletně vybaveno" },
          { label: "Cílová skupina", value: "Young professionals" },
        ],
      },
      {
        id: "sn-3",
        slug: "stredocesky-dum",
        title: "Větší rodinný dům — sdíleně",
        location: "Středočeský kraj – Brandýs n. L.",
        propertyType: "Rodinný dům 5+1",
        priceLabel: "8 000 Kč / osoba",
        image: IMG.houseCountry,
        gallery: [IMG.houseCountry, IMG.houseFamily],
        description: "Pět osob v domě se zahradou — více prostoru než v bytě.",
        badge: "Ukázková nabídka",
        metrics: [
          { label: "Dispozice", value: "5+1" },
          { label: "Počet míst", value: "5" },
          { label: "Nájem celkem", value: "40 000 Kč", emphasize: true },
          { label: "Cena / osoba", value: "8 000 Kč" },
          { label: "Kauce", value: "40 000 Kč" },
          { label: "Energie orientačně", value: "6 500 Kč / měs." },
          { label: "Vybavení", value: "Částečně vybaveno" },
          { label: "Cílová skupina", value: "Sdílená domácnost" },
        ],
      },
      {
        id: "sn-4",
        slug: "ostrava-levny",
        title: "Levnější regionální varianta",
        location: "Ostrava – Poruba",
        propertyType: "Byt 3+1",
        priceLabel: "5 500 Kč / osoba",
        image: IMG.aptCozy,
        gallery: [IMG.aptCozy, IMG.building],
        description: "Tři spolubydlící — nejnižší cena na osobu v modelu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Dispozice", value: "3+1" },
          { label: "Počet míst", value: "3" },
          { label: "Nájem celkem", value: "16 500 Kč", emphasize: true },
          { label: "Cena / osoba", value: "5 500 Kč" },
          { label: "Kauce", value: "16 500 Kč" },
          { label: "Energie orientačně", value: "2 200 Kč / měs." },
          { label: "Vybavení", value: "Základní" },
          { label: "Cílová skupina", value: "Rozpočtově citliví" },
        ],
      },
      {
        id: "sn-5",
        slug: "praha-premium-shared",
        title: "Premium shared living Praha",
        location: "Praha 1 – Nové Město",
        propertyType: "Byt 5+kk · premium",
        priceLabel: "16 000 Kč / osoba",
        image: IMG.aptLuxury,
        gallery: [IMG.aptLuxury, IMG.loft, IMG.aptModern],
        description: "Čtyři osoby, prémiový interiér v centru — vyšší cena, vyšší komfort.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Dispozice", value: "5+kk" },
          { label: "Počet míst", value: "4" },
          { label: "Nájem celkem", value: "64 000 Kč", emphasize: true },
          { label: "Cena / osoba", value: "16 000 Kč" },
          { label: "Kauce", value: "64 000 Kč" },
          { label: "Energie orientačně", value: "7 000 Kč / měs." },
          { label: "Vybavení", value: "Design · plně vybaveno" },
          { label: "Cílová skupina", value: "Premium shared living" },
        ],
      },
    ],
  },
  {
    slug: "nabidnete-cenu",
    title: "Nabídněte cenu",
    seoTitle: "Nabídněte cenu za nemovitost",
    seoDescription:
      "Modelové příklady protinabídek pod inzerovanou cenu — rozdíl v Kč i procentech.",
    subtitle: "Majitel zveřejní cenu, vy můžete nabídnout vlastní částku.",
    explanation:
      "Režim umožňuje zaslat nezávaznou protinabídku. Majitel může nabídku přijmout, odmítnout nebo navrhnout kompromis — bez automatického převodu vlastnictví.",
    benefits: [
      { title: "Prostor k jednání", text: "Nemusíte brát inzerovanou cenu jako finální." },
      { title: "Transparentní rozdíl", text: "Vidíte Kč i % oproti nabídkové ceně." },
      { title: "Kontrola majitele", text: "Rozhodnutí zůstává na straně prodávajícího." },
      { title: "Rychlý přehled", text: "Modelové scénáře ukazují typické rozsahy." },
    ],
    steps: [
      { title: "Prohlédněte cenu", text: "Inzerovaná cena je výchozí bod." },
      { title: "Navrhněte částku", text: "Model ukáže realistický rozdíl." },
      { title: "Počkejte na reakci", text: "Majitel nabídku vyhodnotí." },
    ],
    risks: [
      "Nižší nabídka může být odmítnuta bez vysvětlení prahu.",
      "Nabídka není závazná koupě, dokud nevznikne smlouva.",
      "Tržní cena se může lišit od modelu.",
    ],
    ctaLabel: "Navrhnout vlastní cenu",
    ctaHref: "#zajemn",
    interestMode: "OFFER_PRICE",
    showAmount: true,
    examples: [
      {
        id: "nc-1",
        slug: "hradec-maly",
        title: "Moderní byt — malý rozdíl",
        location: "Hradec Králové – Moravské Předměstí",
        propertyType: "Byt 2+kk · moderní",
        priceLabel: "4 800 000 Kč",
        image: IMG.aptBright,
        gallery: [IMG.aptBright, IMG.aptModern],
        description: "Modelová nabídka jen −2,1 % — jemné vyjednávání.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Prodejní cena", value: "4 800 000 Kč", emphasize: true },
          { label: "Modelová nabídka", value: "4 700 000 Kč" },
          { label: "Rozdíl", value: "−100 000 Kč" },
          { label: "Rozdíl %", value: "−2,1 %" },
          { label: "Typ vyjednávání", value: "Malý rozdíl" },
        ],
        scenario: "Typické u atraktivní nabídky, kde majitel nemá důvod výrazně slevit.",
      },
      {
        id: "nc-2",
        slug: "brno-stredni",
        title: "Rodinný dům — střední rozdíl",
        location: "Brno – Líšeň",
        propertyType: "Rodinný dům",
        priceLabel: "8 900 000 Kč",
        image: IMG.houseFamily,
        gallery: [IMG.houseFamily, IMG.houseExt],
        description: "Nabídka 8 400 000 Kč (−5,6 %).",
        badge: "Modelový příklad",
        metrics: [
          { label: "Prodejní cena", value: "8 900 000 Kč", emphasize: true },
          { label: "Modelová nabídka", value: "8 400 000 Kč" },
          { label: "Rozdíl", value: "−500 000 Kč" },
          { label: "Rozdíl %", value: "−5,6 %" },
          { label: "Typ vyjednávání", value: "Střední rozdíl" },
        ],
      },
      {
        id: "nc-3",
        slug: "ostrava-vetsi",
        title: "Investiční byt — větší rozdíl",
        location: "Ostrava – Zábřeh",
        propertyType: "Byt 3+1 · investiční",
        priceLabel: "3 600 000 Kč",
        image: IMG.aptCozy,
        gallery: [IMG.aptCozy, IMG.building],
        description: "Nabídka 3 300 000 Kč (−8,3 %) — prostor pro jednání.",
        badge: "Ukázková nabídka",
        metrics: [
          { label: "Prodejní cena", value: "3 600 000 Kč", emphasize: true },
          { label: "Modelová nabídka", value: "3 300 000 Kč" },
          { label: "Rozdíl", value: "−300 000 Kč" },
          { label: "Rozdíl %", value: "−8,3 %" },
          { label: "Typ vyjednávání", value: "Větší rozdíl" },
        ],
      },
      {
        id: "nc-4",
        slug: "praha-premium",
        title: "Prémiová vila — vyjednávání",
        location: "Praha 6 – Dejvice",
        propertyType: "Vila · luxus",
        priceLabel: "18 500 000 Kč",
        image: IMG.houseLarge,
        gallery: [IMG.houseLarge, IMG.aptLuxury],
        description: "Nabídka 17 800 000 Kč (−3,8 %) u prémiového segmentu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Prodejní cena", value: "18 500 000 Kč", emphasize: true },
          { label: "Modelová nabídka", value: "17 800 000 Kč" },
          { label: "Rozdíl", value: "−700 000 Kč" },
          { label: "Rozdíl %", value: "−3,8 %" },
          { label: "Typ vyjednávání", value: "Prémiový segment" },
        ],
      },
      {
        id: "nc-5",
        slug: "liberec-starsi",
        title: "Starší objekt — výraznější sleva",
        location: "Liberec – Jeřáb",
        propertyType: "Byt 3+1 · před rekonstrukcí",
        priceLabel: "2 950 000 Kč",
        image: IMG.townhouse,
        gallery: [IMG.townhouse, IMG.aptStudio],
        description: "Nabídka 2 600 000 Kč (−11,9 %) — starší stav, větší sleva.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Prodejní cena", value: "2 950 000 Kč", emphasize: true },
          { label: "Modelová nabídka", value: "2 600 000 Kč" },
          { label: "Rozdíl", value: "−350 000 Kč" },
          { label: "Rozdíl %", value: "−11,9 %" },
          { label: "Typ vyjednávání", value: "Výraznější sleva" },
        ],
      },
    ],
  },
  {
    slug: "aukce",
    title: "Aukce nemovitostí",
    seoTitle: "Aukce nemovitostí",
    seoDescription:
      "Modelové příklady dražeb — vyvolávací cena, odhad a modelový průběh příhozů.",
    subtitle: "Sledujte modelový průběh aukce od vyvolávací po aktuální cenu.",
    explanation:
      "Aukční režim ukazuje vyvolávací cenu, odhadní hodnotu a modelový stav příhozů. Ostrý převod vlastnictví vždy závisí na právních podmínkách konkrétní aukce.",
    benefits: [
      { title: "Transparentní průběh", text: "Vidíte vyvolávací, odhad i modelovou cenu." },
      { title: "Potenciál úspory", text: "Start pod odhadem může být příležitostí." },
      { title: "Časový rámec", text: "Model ukazuje datum ukončení." },
      { title: "Počet příhozů", text: "Aktivita aukce na první pohled." },
    ],
    steps: [
      { title: "Porovnejte ceny", text: "Vyvolávací vs. odhadní vs. modelová." },
      { title: "Sledujte termín", text: "Datum ukončení určuje tempo." },
      { title: "Zjistěte podmínky", text: "Závaznost příhozů se liší případ od případu." },
    ],
    risks: [
      "Nejvyšší příhoz nemusí znamenat automatický převod nemovitosti.",
      "Závaznost příhozů je otevřená právní otázka.",
      "Odhadní cena je orientační, ne znalecký posudek.",
    ],
    ctaLabel: "Zjistit více o aukci",
    ctaHref: "#zajemn",
    interestMode: "AUCTION",
    showAmount: true,
    examples: [
      {
        id: "au-1",
        slug: "praha-byt-aukce",
        title: "Byt Praha — modelová aukce",
        location: "Praha 10 – Vršovice",
        propertyType: "Byt 2+kk",
        priceLabel: "Model 5 450 000 Kč",
        image: IMG.aptModern,
        gallery: [IMG.aptModern, IMG.loft],
        description: "Vyvolávací pod odhadem, aktivní modelové příhozy.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Odhadní cena", value: "6 200 000 Kč" },
          { label: "Vyvolávací cena", value: "4 900 000 Kč", emphasize: true },
          { label: "Modelová cena", value: "5 450 000 Kč" },
          { label: "Rozdíl vs. odhad", value: "−750 000 Kč" },
          { label: "Ukončení", value: "15. 10. 2026" },
          { label: "Modelové příhozy", value: "12" },
        ],
      },
      {
        id: "au-2",
        slug: "brno-dum-aukce",
        title: "Rodinný dům Brno",
        location: "Brno – Komín",
        propertyType: "Rodinný dům",
        priceLabel: "Model 7 850 000 Kč",
        image: IMG.houseExt,
        gallery: [IMG.houseExt, IMG.houseFamily],
        description: "Vyvolávací 7 000 000 Kč při odhadu 9 000 000 Kč.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Odhadní cena", value: "9 000 000 Kč" },
          { label: "Vyvolávací cena", value: "7 000 000 Kč", emphasize: true },
          { label: "Modelová cena", value: "7 850 000 Kč" },
          { label: "Rozdíl vs. odhad", value: "−1 150 000 Kč" },
          { label: "Ukončení", value: "22. 10. 2026" },
          { label: "Modelové příhozy", value: "8" },
        ],
      },
      {
        id: "au-3",
        slug: "plzen-pozemek-aukce",
        title: "Pozemek Plzeň",
        location: "Plzeň – Radčice",
        propertyType: "Pozemek · stavební",
        priceLabel: "Model 3 950 000 Kč",
        image: IMG.land,
        gallery: [IMG.land, IMG.invest],
        description: "Stavební pozemek — odhad 4 500 000 Kč.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Odhadní cena", value: "4 500 000 Kč" },
          { label: "Vyvolávací cena", value: "3 500 000 Kč", emphasize: true },
          { label: "Modelová cena", value: "3 950 000 Kč" },
          { label: "Rozdíl vs. odhad", value: "−550 000 Kč" },
          { label: "Ukončení", value: "12. 11. 2026" },
          { label: "Modelové příhozy", value: "6" },
        ],
      },
      {
        id: "au-4",
        slug: "sumava-rekreace-aukce",
        title: "Rekreační chata Šumava",
        location: "Jihočeský kraj – Šumava",
        propertyType: "Rekreační objekt",
        priceLabel: "Model 2 150 000 Kč",
        image: IMG.cabin,
        gallery: [IMG.cabin, IMG.farm],
        description: "Odhad 2 800 000 Kč, start 1 900 000 Kč — sezónní objekt.",
        badge: "Ukázková nabídka",
        metrics: [
          { label: "Odhadní cena", value: "2 800 000 Kč" },
          { label: "Vyvolávací cena", value: "1 900 000 Kč", emphasize: true },
          { label: "Modelová cena", value: "2 150 000 Kč" },
          { label: "Rozdíl vs. odhad", value: "−650 000 Kč" },
          { label: "Ukončení", value: "5. 11. 2026" },
          { label: "Modelové příhozy", value: "18" },
        ],
      },
      {
        id: "au-5",
        slug: "olomouc-dum-aukce",
        title: "Bytový dům Olomouc",
        location: "Olomouc – Hodolany",
        propertyType: "Bytový dům · investiční",
        priceLabel: "Model 12 800 000 Kč",
        image: IMG.skyline,
        gallery: [IMG.skyline, IMG.townhouse],
        description: "Odhad 15 000 000 Kč, vyvolávací 11 500 000 Kč.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Odhadní cena", value: "15 000 000 Kč" },
          { label: "Vyvolávací cena", value: "11 500 000 Kč", emphasize: true },
          { label: "Modelová cena", value: "12 800 000 Kč" },
          { label: "Rozdíl vs. odhad", value: "−2 200 000 Kč" },
          { label: "Ukončení", value: "30. 10. 2026" },
          { label: "Modelové příhozy", value: "9" },
        ],
      },
    ],
  },
  {
    slug: "bydleni-za-vypomoc",
    title: "Bydlení za výpomoc",
    seoTitle: "Bydlení za výpomoc",
    seoDescription:
      "Modelové příklady bydlení se sníženým nájmem výměnou za domluvenou pomoc.",
    subtitle: "Nižší nájem výměnou za jasně definovanou pomoc.",
    explanation:
      "Majitel nabízí bydlení se sníženým nájmem (nebo bezplatně) výměnou za dohodnutou výpomoc — zahradu, údržbu, péči o zvířata nebo správu objektu. Konkrétní právní a pracovní vztah musí být řešen individuálně; model je pouze ilustrativní.",
    benefits: [
      { title: "Úspora na nájmu", text: "Model ukáže rozdíl oproti standardní ceně." },
      { title: "Jasný rozsah pomoci", text: "Hodiny a typ výpomoci předem." },
      { title: "Různé lokality", text: "Od okolí Prahy po horské objekty." },
      { title: "Transparentní podmínky", text: "Bez skrytých očekávání v modelu." },
    ],
    steps: [
      { title: "Porovnejte nájem", text: "Standardní vs. model za výpomoc." },
      { title: "Ověřte rozsah", text: "Hodiny a typ práce měsíčně." },
      { title: "Domluvte smlouvu", text: "Právní rámec vždy individuálně." },
    ],
    risks: [
      "Pracovněprávní a daňové dopady řešte individuálně — model není doporučení.",
      "Rozsah výpomoci musí být písemně jasný.",
      "Ukončení bydlení a výpomoci může být vázáno na stejnou smlouvu.",
    ],
    ctaLabel: "Mám o tuto možnost zájem",
    ctaHref: "#zajemn",
    interestMode: "HOUSING_HELP",
    examples: [
      {
        id: "bv-1",
        slug: "praha-zahrada",
        title: "Zahrada a údržba — Praha okolí",
        location: "Středočeský kraj – Říčany",
        propertyType: "Rodinný dům",
        priceLabel: "9 000 Kč / měs.",
        image: IMG.houseFamily,
        gallery: [IMG.houseFamily, IMG.houseExt],
        description: "Zahrada a drobná údržba — cca 20 hod/měsíc.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Standardní nájem", value: "20 000 Kč" },
          { label: "Nájem za výpomoc", value: "9 000 Kč", emphasize: true },
          { label: "Úspora", value: "11 000 Kč / měs." },
          { label: "Čas pomoci", value: "cca 20 hod / měs." },
          { label: "Typ výpomoci", value: "Zahrada + drobná údržba" },
        ],
      },
      {
        id: "bv-2",
        slug: "vysocina-zvirata",
        title: "Péče o statek a zvířata",
        location: "Kraj Vysočina – Telč okolí",
        propertyType: "Statek",
        priceLabel: "6 000 Kč / měs.",
        image: IMG.farm,
        gallery: [IMG.farm, IMG.houseCountry],
        description: "Pomoc se zvířaty — výrazně snížený nájem.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Standardní nájem", value: "18 000 Kč" },
          { label: "Nájem za výpomoc", value: "6 000 Kč", emphasize: true },
          { label: "Úspora", value: "12 000 Kč / měs." },
          { label: "Čas pomoci", value: "cca 30 hod / měs." },
          { label: "Typ výpomoci", value: "Péče o zvířata / statek" },
        ],
      },
      {
        id: "bv-3",
        slug: "olomouc-sprava",
        title: "Správa bytového domu",
        location: "Olomouc – Lazce",
        propertyType: "Správa domu + bydlení",
        priceLabel: "8 000 Kč / měs.",
        image: IMG.townhouse,
        gallery: [IMG.townhouse, IMG.skyline],
        description: "Bydlení spojené se správou menšího domu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Standardní nájem", value: "16 000 Kč" },
          { label: "Nájem za výpomoc", value: "8 000 Kč", emphasize: true },
          { label: "Úspora", value: "8 000 Kč / měs." },
          { label: "Čas pomoci", value: "cca 18 hod / měs." },
          { label: "Typ výpomoci", value: "Správa objektu" },
        ],
      },
      {
        id: "bv-4",
        slug: "pardubice-senior",
        title: "Pomoc seniorovi / domácnosti",
        location: "Pardubice – Polabiny",
        propertyType: "Byt 3+1 u seniora",
        priceLabel: "4 500 Kč / měs.",
        image: IMG.seniorHome,
        gallery: [IMG.seniorHome, IMG.aptCozy],
        description:
          "Nízký nájem výměnou za pomoc v domácnosti a doprovod — právní vztah řešte individuálně.",
        badge: "Ukázková nabídka",
        metrics: [
          { label: "Standardní nájem", value: "14 000 Kč" },
          { label: "Nájem za výpomoc", value: "4 500 Kč", emphasize: true },
          { label: "Úspora", value: "9 500 Kč / měs." },
          { label: "Čas pomoci", value: "cca 25 hod / měs." },
          { label: "Typ výpomoci", value: "Pomoc seniorovi / domácnost" },
        ],
      },
      {
        id: "bv-5",
        slug: "beskydy-objekt",
        title: "Údržba rekreační nemovitosti",
        location: "Moravskoslezský kraj – Beskydy",
        propertyType: "Chata · sezónní",
        priceLabel: "5 000 Kč / měs.",
        image: IMG.cabin,
        gallery: [IMG.cabin, IMG.farm],
        description: "Údržba a příprava objektu pro hosty.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Standardní nájem", value: "15 000 Kč" },
          { label: "Nájem za výpomoc", value: "5 000 Kč", emphasize: true },
          { label: "Úspora", value: "10 000 Kč / měs." },
          { label: "Čas pomoci", value: "cca 25 hod / měs." },
          { label: "Typ výpomoci", value: "Údržba rekreační nemovitosti" },
        ],
      },
    ],
  },
  {
    slug: "smena",
    title: "Směna nemovitostí",
    seoTitle: "Směna nemovitostí",
    seoDescription:
      "Modelové příklady výměny nemovitostí s doplatkem — porovnání A ↔ B.",
    subtitle: "Místo klasického prodeje směňte nemovitost za jinou, případně s doplatkem.",
    explanation:
      "Majitel nabízí směnu své nemovitosti za jinou. Rozdíl hodnot se řeší doplatkem. Přijetí modelu znamená pokračování v jednání, nikoli okamžitý převod.",
    benefits: [
      { title: "Bez dvojího prodeje", text: "Jedna transakční logika místo dvou." },
      { title: "Jasný doplatek", text: "Rozdíl hodnot je vidět hned." },
      { title: "Porovnání A ↔ B", text: "Obě strany na jedné kartě." },
      { title: "Flexibilní scénáře", text: "Byt za dům, pozemek za byt i multi-asset." },
    ],
    steps: [
      { title: "Porovnejte strany", text: "Levá a pravá nemovitost vedle sebe." },
      { title: "Spočítejte doplatek", text: "Kdo doplácí a kolik." },
      { title: "Jednejte dál", text: "Model není smlouva o směně." },
    ],
    risks: [
      "Nepeněžní položky nemusí být nemovitosti.",
      "Daňové a právní dopady směny řešte individuálně.",
      "Hodnoty v modelu jsou ilustrativní.",
    ],
    ctaLabel: "Mám o tuto možnost zájem",
    ctaHref: "#zajemn",
    interestMode: "SWAP",
    examples: [
      {
        id: "sm-1",
        slug: "praha-stredocesky",
        title: "Byt Praha ↔ Dům Středočeský kraj",
        location: "Praha / Středočeský kraj",
        propertyType: "Směna · byt za dům",
        priceLabel: "Doplatek 1 500 000 Kč",
        image: IMG.aptLuxury,
        description: "Byt 7M za dům 8,5M — doplatek na straně bytu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Doplatek", value: "1 500 000 Kč", emphasize: true },
          { label: "Směr doplatku", value: "Majitel bytu → majitel domu" },
          { label: "Proč směna", value: "Město → zahrada a prostor" },
        ],
        swap: {
          left: {
            title: "Byt Praha",
            location: "Praha 8 – Karlín",
            propertyType: "Byt 3+kk",
            valueLabel: "7 000 000 Kč",
            image: IMG.aptLuxury,
          },
          right: {
            title: "Rodinný dům",
            location: "Středočeský kraj – Brandýs n. L.",
            propertyType: "Rodinný dům",
            valueLabel: "8 500 000 Kč",
            image: IMG.houseFamily,
          },
          settlementLabel: "Doplatek 1 500 000 Kč",
        },
      },
      {
        id: "sm-2",
        slug: "ostrava-2byty",
        title: "Dům Ostrava ↔ 2 byty",
        location: "Ostrava",
        propertyType: "Směna · dům za 2 byty",
        priceLabel: "Rozdíl 400 000 Kč",
        image: IMG.houseExt,
        description: "Dům 6M za dva byty dohromady 6,4M.",
        badge: "Ukázková nabídka",
        metrics: [
          { label: "Doplatek", value: "400 000 Kč", emphasize: true },
          { label: "Směr doplatku", value: "Majitel domu → majitel bytů" },
          { label: "Proč směna", value: "Jeden objekt → diverzifikace" },
        ],
        swap: {
          left: {
            title: "Dům Ostrava",
            location: "Ostrava – Poruba",
            propertyType: "Rodinný dům",
            valueLabel: "6 000 000 Kč",
            image: IMG.houseExt,
          },
          right: {
            title: "2 byty",
            location: "Ostrava – Centrum",
            propertyType: "2× byt",
            valueLabel: "6 400 000 Kč",
            image: IMG.aptBright,
          },
          settlementLabel: "Doplatek 400 000 Kč",
        },
      },
      {
        id: "sm-3",
        slug: "praha-apartman-byt",
        title: "Byt Praha ↔ Apartmán + doplatek",
        location: "Praha / Krkonoše",
        propertyType: "Směna · byt za apartmán",
        priceLabel: "Doplatek 800 000 Kč",
        image: IMG.loft,
        description: "Byt 7,8M za horský apartmán 7M — doplatek 800 tis. majiteli bytu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Doplatek", value: "800 000 Kč", emphasize: true },
          { label: "Směr doplatku", value: "Majitel apartmánu → majitel bytu" },
          { label: "Proč směna", value: "Městské bydlení → rekreační výnos" },
        ],
        swap: {
          left: {
            title: "Byt Praha",
            location: "Praha 2 – Vinohrady",
            propertyType: "Byt 3+kk",
            valueLabel: "7 800 000 Kč",
            image: IMG.loft,
          },
          right: {
            title: "Apartmán Krkonoše",
            location: "Špindlerův Mlýn",
            propertyType: "Apartmán",
            valueLabel: "7 000 000 Kč",
            image: IMG.cabin,
          },
          settlementLabel: "Doplatek 800 000 Kč (k bytu)",
        },
      },
      {
        id: "sm-4",
        slug: "pozemek-byt",
        title: "Pozemek ↔ Byt + doplatek",
        location: "Plzeňský kraj / Plzeň",
        propertyType: "Směna · pozemek za byt",
        priceLabel: "Doplatek 1 000 000 Kč",
        image: IMG.land,
        description: "Pozemek 5M za byt 4M + doplatek 1M majiteli pozemku.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Doplatek", value: "1 000 000 Kč", emphasize: true },
          { label: "Směr doplatku", value: "Majitel bytu → majitel pozemku" },
          { label: "Proč směna", value: "Stavební záměr → hotové bydlení" },
        ],
        swap: {
          left: {
            title: "Pozemek",
            location: "Plzeňský kraj",
            propertyType: "Pozemek",
            valueLabel: "5 000 000 Kč",
            image: IMG.land,
          },
          right: {
            title: "Byt Plzeň",
            location: "Plzeň – Lochotín",
            propertyType: "Byt 3+kk",
            valueLabel: "4 000 000 Kč",
            image: IMG.aptCozy,
          },
          settlementLabel: "Doplatek 1 000 000 Kč (k pozemku)",
        },
      },
      {
        id: "sm-5",
        slug: "dum-za-mensi-dum",
        title: "Větší dům ↔ menší dům + finance",
        location: "Brno / okolí Brna",
        propertyType: "Směna · downsize + cash",
        priceLabel: "Doplatek 2 200 000 Kč",
        image: IMG.houseLarge,
        description:
          "Větší dům 9,5M za menší dům 7,3M — majitel většího dostane doplatek 2,2M.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Doplatek", value: "2 200 000 Kč", emphasize: true },
          { label: "Směr doplatku", value: "Majitel menšího → majitel většího" },
          { label: "Proč směna", value: "Downsize + uvolnění kapitálu" },
        ],
        swap: {
          left: {
            title: "Větší dům Brno",
            location: "Brno – Žabovřesky",
            propertyType: "Rodinný dům 6+1",
            valueLabel: "9 500 000 Kč",
            image: IMG.houseLarge,
          },
          right: {
            title: "Menší dům okolí",
            location: "Kuřim",
            propertyType: "Rodinný dům 4+1",
            valueLabel: "7 300 000 Kč",
            image: IMG.houseCountry,
          },
          settlementLabel: "Doplatek 2 200 000 Kč (k většímu domu)",
        },
      },
    ],
  },
  {
    slug: "zahranicni",
    title: "Zahraniční nemovitosti",
    seoTitle: "Zahraniční nemovitosti",
    seoDescription:
      "Modelové nabídky mimo ČR — cena v místní měně, orientační CZK a výnos. Ilustrativní scénáře.",
    subtitle: "Orientace v zahraničních příležitostech s jasnou měnou a lokalitou.",
    explanation:
      "Zahraniční nabídky mají vlastní měnu, právní režim a daňová pravidla. Přepočet do CZK je orientační. Neprezentujeme právní ani investiční parametry jako garantované.",
    benefits: [
      { title: "Měna originálu", text: "Cena v EUR, AED nebo USD — ne jen CZK." },
      { title: "Orientační výnos", text: "Modelový nájem a yield, pokud dává smysl." },
      { title: "Geografický mix", text: "Evropa, Blízký východ i Asie." },
      { title: "Upozornění na režim", text: "Vlastnictví se liší zemi od země." },
    ],
    steps: [
      { title: "Zvolte zemi", text: "Podívejte se na lokalitu a měnu." },
      { title: "Porovnejte CZK", text: "Orientační přepočet pro představu." },
      { title: "Ověřte právní režim", text: "Vlastnictví a daně řešte lokálně." },
    ],
    risks: [
      "Kurzové riziko — CZK přepočet se mění.",
      "Vlastnický režim pro cizince se liší (např. omezení, leasehold).",
      "Výnosy a nájmy nejsou garantované.",
    ],
    ctaLabel: "Mám o tuto možnost zájem",
    ctaHref: "#zajemn",
    interestMode: "FOREIGN_INFO",
    examples: [
      {
        id: "za-1",
        slug: "spanelsko-costa",
        title: "Apartmán — Costa del Sol",
        location: "Španělsko · Marbella okolí",
        propertyType: "Apartmán · holiday rental",
        priceLabel: "250 000 EUR",
        currency: "EUR",
        image: IMG.coast,
        gallery: [IMG.coast, IMG.croatia],
        description: "Přímořský apartmán — modelový krátkodobý nájem.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Cena", value: "250 000 EUR", emphasize: true },
          { label: "Orientačně CZK", value: "cca 6 250 000 Kč" },
          { label: "Odhad nájmu", value: "1 400 EUR / měs." },
          { label: "Orientační výnos", value: "cca 6,7 %" },
          { label: "Vlastnický režim", value: "Freehold (ověřit lokálně)" },
          { label: "Cílové využití", value: "Holiday / krátkodobý pronájem" },
        ],
      },
      {
        id: "za-2",
        slug: "dubai-studio",
        title: "Studio / 1BR — Dubai",
        location: "Spojené arabské emiráty · Dubai Marina",
        propertyType: "Studio / 1BR · city yield",
        priceLabel: "1 100 000 AED",
        currency: "AED",
        image: IMG.dubai,
        gallery: [IMG.dubai, IMG.skyline],
        description: "Modelový výnos z dlouhodobého pronájmu v Marině.",
        badge: "Ukázková nabídka",
        metrics: [
          { label: "Cena", value: "1 100 000 AED", emphasize: true },
          { label: "Orientačně CZK", value: "cca 7 150 000 Kč" },
          { label: "Odhad nájmu", value: "75 000 AED / rok" },
          { label: "Orientační výnos", value: "cca 6,8 %" },
          { label: "Upozornění", value: "Freehold zóny — ověřit zónu" },
          { label: "Cílové využití", value: "Long-term rental" },
        ],
      },
      {
        id: "za-3",
        slug: "chorvatsko-more",
        title: "Apartmán u moře — Chorvatsko",
        location: "Chorvatsko · Dalmácie",
        propertyType: "Apartmán · sezónní",
        priceLabel: "220 000 EUR",
        currency: "EUR",
        image: IMG.croatia,
        gallery: [IMG.croatia, IMG.coast],
        description: "Sezónní apartmán blízko pobřeží.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Cena", value: "220 000 EUR", emphasize: true },
          { label: "Orientačně CZK", value: "cca 5 500 000 Kč" },
          { label: "Odhad nájmu", value: "1 100 EUR / měs. prům." },
          { label: "Orientační výnos", value: "cca 6,0 %" },
          { label: "Upozornění", value: "Sezónnost silně ovlivní cashflow" },
          { label: "Cílové využití", value: "Sezónní turistika" },
        ],
      },
      {
        id: "za-4",
        slug: "italie-dum",
        title: "Dům / apartmán — Itálie",
        location: "Itálie · Apulie",
        propertyType: "Dům · rekonstrukční potenciál",
        priceLabel: "180 000 EUR",
        currency: "EUR",
        image: IMG.italy,
        gallery: [IMG.italy, IMG.houseCountry],
        description: "Menší objekt v jižní Itálii — rekonstrukční potenciál.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Cena", value: "180 000 EUR", emphasize: true },
          { label: "Orientačně CZK", value: "cca 4 500 000 Kč" },
          { label: "Odhad nájmu", value: "750 EUR / měs." },
          { label: "Orientační výnos", value: "cca 5,0 %" },
          { label: "Upozornění", value: "Notářské a daňové náklady navíc" },
          { label: "Cílové využití", value: "Value-add / rekonstrukce" },
        ],
      },
      {
        id: "za-5",
        slug: "bali-villa",
        title: "Villa — Bali",
        location: "Indonésie · Bali · Canggu",
        propertyType: "Villa · short-term",
        priceLabel: "190 000 USD",
        currency: "USD",
        image: IMG.bali,
        gallery: [IMG.bali, IMG.coast],
        description: "Villa na leasehold — krátkodobý nájem v modelu.",
        badge: "Modelový příklad",
        metrics: [
          { label: "Cena", value: "190 000 USD", emphasize: true },
          { label: "Orientačně CZK", value: "cca 4 370 000 Kč" },
          { label: "Odhad nájmu", value: "1 800 USD / měs." },
          { label: "Orientační výnos", value: "cca 11 %" },
          { label: "Vlastnický režim", value: "Leasehold — ověřit délku" },
          { label: "Cílové využití", value: "Investiční short-term" },
        ],
      },
    ],
  },
];
