import type { MarketPlugin } from "@/domains/markets/plugins/types";

export const hrMarketPlugin: MarketPlugin = {
  marketCode: "HR",
  definition: {
    marketCode: "HR",
    countryCode: "HR",
    displayNameEn: "Croatia",
    displayNameLocal: "Hrvatska",
    defaultLocale: "hr-HR",
    supportedLocales: ["hr-HR", "en-GB"],
    defaultCurrency: "EUR",
    timezone: "Europe/Zagreb",
    measurementSystem: "METRIC",
    enabled: false,
    launchStatus: "PLANNED",
    regulatoryConfigVersion: "hr-reg.planned",
    hasMinimumPublicData: false,
  },
  property: {
    areaUnit: "sqm",
    supportedPropertyTypes: ["APARTMENT", "HOUSE", "LAND", "OTHER"],
    addressModel: "EU_STREET",
    titleDeedLabelEn: "Zemljišne knjige / title extract",
    layoutNotation: "BEDROOM_COUNT",
    detailSectionExtraIds: [],
    searchFilterExtraKeys: ["bedrooms", "bathrooms"],
  },
  transactionCosts: {
    packId: "hr-tx-costs.planned",
    buyerClosingCostBpsEstimate: 600,
    sellerClosingCostBpsEstimate: 350,
    transferTaxLabelEn: "Real estate transfer tax (illustrative)",
    notesEn: "Tourism / coastal inventory bias — data pack TBD.",
  },
  financing: {
    mortgageAvailable: true,
    partnerHandoffEnabled: false,
    typicalLtvMaxPct: 80,
    rateBenchmarkLabelEn: null,
    currency: "EUR",
    primaryProviderCode: null,
  },
  taxation: {
    standardVatRateBp: 2500,
    propertyTaxModel: "TRANSFER_ONLY",
    rentalIncomeTaxNotesEn: "Pending HR regulatory pack.",
    regulatoryPackId: "hr-tax.planned",
    taxPluginId: null,
  },
  regulatory: {
    rulesVersion: "hr-reg.planned",
    renovationCatalogAvailable: false,
    valuationModelCodes: [],
  },
  capabilities: {
    PROPERTY_SEARCH: "NOT_AVAILABLE",
    VALUATION: "NOT_AVAILABLE",
    INVESTMENT_ENGINE: "NOT_AVAILABLE",
    MORTGAGE_CALCULATOR: "NOT_AVAILABLE",
    MORTGAGE_LEAD_HANDOFF: "NOT_AVAILABLE",
    COMPARISON: "NOT_AVAILABLE",
    LOCATION_INTELLIGENCE: "NOT_AVAILABLE",
    LISTING_BOOST: "NOT_AVAILABLE",
    B2B_CRM: "NOT_AVAILABLE",
    QUALIFIED_LEADS: "NOT_AVAILABLE",
    TAX_ESTIMATES: "NOT_AVAILABLE",
    TRANSACTION_COST_ESTIMATES: "NOT_AVAILABLE",
    PROFESSIONAL_SERVICES: "NOT_AVAILABLE",
  },
  featureFlagDefaults: {
    MARKET_HR_VALUATION_ENABLED: false,
  },
};
