/**
 * Canonical demo catalog mapped to PublicPropertyDto (Prompt 7 Part 5).
 * Used by UI when DB seed is not available; seed script mirrors these rows.
 */

import type { PropertyRecord } from "@/domains/properties/service/dto";
import { formatAreaConflict } from "@/domains/properties/service/field-conflicts";
import {
  toPublicPropertyDto,
  type PublicPropertyDto,
} from "@/domains/properties/service/dto";
import { canViewProperty } from "@/domains/properties/service/authorization";

const daysAgo = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

const areaConflict = formatAreaConflict([
  { value: 72, sourceLabel: "Partner feed" },
  { value: 74, sourceLabel: "Portál" },
]);

/** Rich canonical records for demo (isDemo: true). */
export const DEMO_PROPERTY_RECORDS: PropertyRecord[] = [
  {
    id: "demo-apt-vinohrady",
    slug: "demo-byt-3kk-vinohrady",
    status: "ACTIVE",
    visibility: "PUBLIC",
    transactionType: "SALE",
    title: "Ukázkový byt 3+kk (demo)",
    description:
      "Demonstrační byt s kompletními daty — cena, lokalita, plocha i historie. Slouží k ověření UI, ne jako nabídka k prodeji.",
    propertyType: "APARTMENT",
    askingPrice: 6_490_000,
    currency: "CZK",
    pricePerSqm: 87_703,
    usableArea: 74,
    layout: "3+kk",
    condition: "GOOD",
    ownershipType: "PERSONAL",
    energyRating: "C",
    floor: 3,
    floorsTotal: 5,
    hasElevator: true,
    publicLabel: "Praha 2 — Vinohrady (demo)",
    addressPrecision: "EXACT",
    publicCity: "Praha",
    publicDistrict: "Vinohrady",
    publicRegion: "Hlavní město Praha",
    street: "Korunní",
    houseNumber: "100",
    latitude: 50.075,
    longitude: 14.447,
    publishedAt: daysAgo(20),
    updatedAt: daysAgo(1),
    lastSeenAt: daysAgo(1),
    freshness: "FRESH",
    isDemo: true,
    dataQuality: "estimated",
    tags: ["Pronájem", "Centrum"],
    completenessScore: 92,
    grossYieldPct: 5.4,
    cashFlowMonthlyCzk: 2_400,
    majetioScore: 72,
    risk: "medium",
    fieldConflicts: areaConflict ? [areaConflict] : [],
    priceHistory: [
      {
        amount: 6_790_000,
        currency: "CZK",
        changeType: "INITIAL",
        observedAt: daysAgo(60),
        sourceLabel: "Partner feed",
      },
      {
        amount: 6_490_000,
        currency: "CZK",
        changeType: "DECREASED",
        observedAt: daysAgo(12),
        sourceLabel: "Partner feed",
      },
    ],
    sources: [
      {
        provider: "partner:demo-feed",
        sourceType: "PARTNER_FEED",
        lastSeenAt: daysAgo(1),
        lastFetchedAt: daysAgo(1),
        freshness: "FRESH",
        isPrimary: true,
      },
      {
        provider: "portal:demo",
        sourceType: "PUBLIC_PORTAL",
        lastSeenAt: daysAgo(3),
        lastFetchedAt: daysAgo(3),
        freshness: "FRESH",
        isPrimary: false,
      },
    ],
    media: [
      {
        url: "/brand/social/majetio-og-brand.png",
        type: "PHOTO",
        isPrimary: true,
        isPlaceholder: false,
        alt: "Obývací pokoj — demo",
        licenseStatus: "OWNED",
      },
      {
        url: "/brand/logo/majetio-logo-primary.svg",
        type: "PHOTO",
        isPrimary: false,
        isPlaceholder: false,
        alt: "Další foto — demo",
        licenseStatus: "LICENSED",
      },
      {
        url: "/brand/social/majetio-og-brand.png",
        type: "PHOTO",
        isPrimary: false,
        isPlaceholder: false,
        alt: "Chráněná fotografie",
        licenseStatus: "PROHIBITED",
        sourceId: "src-secret-media-1",
      },
    ],
    internalNotes: "INTERNAL: do not show",
    canonicalKey: "demo:byt-3kk-vinohrady",
  },
  {
    id: "demo-house-reno",
    slug: "demo-dum-rekonstrukce",
    status: "ACTIVE",
    visibility: "PUBLIC",
    transactionType: "SALE",
    title: "Ukázkový dům k rekonstrukci (demo)",
    description:
      "Dům ve stavu vyžadujícím rekonstrukci — nižší skóre, vyšší riziko, neúplná data (chybí energetický štítek).",
    propertyType: "HOUSE",
    askingPrice: 12_400_000,
    currency: "CZK",
    pricePerSqm: 77_500,
    usableArea: 160,
    layout: "5+1",
    condition: "NEEDS_RENOVATION",
    ownershipType: "PERSONAL",
    energyRating: "G",
    floor: null,
    floorsTotal: 2,
    hasElevator: false,    publicLabel: "Demonstrační lokalita — Brno-venkov",
    addressPrecision: "APPROXIMATE",
    publicCity: "Šlapanice",
    publicDistrict: null,
    publicRegion: "Jihomoravský kraj",
    publishedAt: daysAgo(40),
    updatedAt: daysAgo(8),
    lastSeenAt: daysAgo(8),
    freshness: "STALE",
    isDemo: true,
    dataQuality: "incomplete",
    tags: ["Rekonstrukce", "Dům"],
    completenessScore: 58,
    grossYieldPct: 2.1,
    cashFlowMonthlyCzk: -1_800,
    majetioScore: 48,
    risk: "high",
    priceHistory: [
      {
        amount: 12_400_000,
        currency: "CZK",
        changeType: "INITIAL",
        observedAt: daysAgo(40),
        sourceLabel: "Manuální vstup",
      },
    ],
    sources: [
      {
        provider: "manual",
        sourceType: "MANUAL",
        lastSeenAt: daysAgo(8),
        lastFetchedAt: daysAgo(8),
        freshness: "STALE",
        isPrimary: true,
      },
    ],
    media: [],
    canonicalKey: "demo:dum-rekonstrukce",
  },
  {
    id: "demo-apt-brno",
    slug: "demo-byt-2kk-brno",
    status: "ACTIVE",
    visibility: "PUBLIC",
    transactionType: "SALE",
    title: "Ukázkový byt 2+kk (demo)",
    description: "Kompletnější Brno demo s čerstvými daty.",
    propertyType: "APARTMENT",
    askingPrice: 4_200_000,
    currency: "CZK",
    pricePerSqm: 80_769,
    usableArea: 52,
    layout: "2+kk",
    condition: "EXCELLENT",
    ownershipType: "PERSONAL",
    energyRating: "B",
    floor: 2,
    floorsTotal: 4,
    hasElevator: true,
    publicLabel: "Brno — střed (demo)",
    addressPrecision: "APPROXIMATE",
    publicCity: "Brno",
    publicDistrict: "Brno-střed",
    publicRegion: "Jihomoravský kraj",
    publishedAt: daysAgo(10),
    updatedAt: daysAgo(0),
    lastSeenAt: daysAgo(0),
    freshness: "FRESH",
    isDemo: true,
    dataQuality: "estimated",
    tags: ["Pronájem", "Brno"],
    completenessScore: 85,
    grossYieldPct: 5.2,
    cashFlowMonthlyCzk: 3_100,
    majetioScore: 76,
    risk: "low",
    priceHistory: [
      {
        amount: 4_350_000,
        currency: "CZK",
        changeType: "INITIAL",
        observedAt: daysAgo(45),
        sourceLabel: "Partner feed",
      },
      {
        amount: 4_200_000,
        currency: "CZK",
        changeType: "DECREASED",
        observedAt: daysAgo(5),
        sourceLabel: "Partner feed",
      },
    ],
    sources: [
      {
        provider: "partner:demo-feed",
        sourceType: "PARTNER_FEED",
        lastSeenAt: daysAgo(0),
        lastFetchedAt: daysAgo(0),
        freshness: "FRESH",
        isPrimary: true,
      },
    ],
    media: [
      {
        url: "/brand/social/majetio-og-brand.png",
        type: "PHOTO",
        isPrimary: true,
        isPlaceholder: false,
        alt: "Náhled demo bytu Brno",
        licenseStatus: "OWNED",
      },
    ],
    canonicalKey: "demo:byt-2kk-brno",
  },
  {
    id: "demo-apt-incomplete",
    slug: "demo-byt-2kk-nizka-cena",
    status: "ACTIVE",
    visibility: "PUBLIC",
    transactionType: "SALE",
    title: "Ukázkový byt 2+kk — nízká cena (demo)",
    description: "Neúplná data: chybí popis lokalitních metrik a energetický štítek.",
    propertyType: "APARTMENT",
    askingPrice: 3_890_000,
    currency: "CZK",
    pricePerSqm: 81_042,
    usableArea: 48,
    layout: "2+kk",
    condition: "AVERAGE",
    ownershipType: "COOPERATIVE",
    energyRating: null,
    floor: 1,
    floorsTotal: 3,
    hasElevator: false,
    publicLabel: "Demonstrační lokalita",
    addressPrecision: "HIDDEN",
    publicCity: "Ostrava",
    street: "Skrytá",
    houseNumber: "9",
    publishedAt: daysAgo(25),
    updatedAt: daysAgo(25),
    lastSeenAt: daysAgo(25),
    freshness: "STALE",
    isDemo: true,
    dataQuality: "incomplete",
    tags: ["Neúplná data", "Sleva"],
    completenessScore: 42,
    grossYieldPct: 6.8,
    cashFlowMonthlyCzk: -2_200,
    majetioScore: 49,
    risk: "high",
    priceHistory: [],
    sources: [
      {
        provider: "portal:demo",
        sourceType: "PUBLIC_PORTAL",
        lastSeenAt: daysAgo(25),
        lastFetchedAt: daysAgo(25),
        freshness: "STALE",
        isPrimary: true,
      },
    ],
    media: [],
    canonicalKey: "demo:byt-nizka-cena",
  },
  {
    id: "demo-apt-unavailable",
    slug: "demo-byt-nedostupny",
    status: "UNAVAILABLE",
    visibility: "PUBLIC",
    transactionType: "SALE",
    title: "Ukázkový byt — již nedostupný (demo)",
    description: "Nabídka zůstává viditelná s upozorněním, že už nemusí být na trhu.",
    propertyType: "APARTMENT",
    askingPrice: 5_100_000,
    currency: "CZK",
    pricePerSqm: 85_000,
    usableArea: 60,
    layout: "2+1",
    condition: "GOOD",
    ownershipType: "PERSONAL",
    energyRating: "D",
    floor: 4,
    floorsTotal: 6,
    hasElevator: true,
    publicLabel: "Praha — Holešovice (demo)",
    addressPrecision: "CITY",
    publicCity: "Praha",
    publicDistrict: "Holešovice",
    isDemo: true,
    dataQuality: "stale",
    tags: ["Nedostupné"],
    media: [],
    priceHistory: [],
    sources: [],
    canonicalKey: "demo:byt-nedostupny",
  },
  {
    id: "demo-apt-archived",
    slug: "demo-byt-archiv",
    status: "ARCHIVED",
    visibility: "PUBLIC",
    transactionType: "SALE",
    title: "Ukázkový byt — archiv (demo)",
    description: "Archivovaná nabídka pro ověření stavu v UI.",
    propertyType: "APARTMENT",
    askingPrice: 4_800_000,
    currency: "CZK",
    usableArea: 55,
    layout: "2+kk",
    condition: "GOOD",
    ownershipType: "PERSONAL",
    publicLabel: "Brno (archiv demo)",
    addressPrecision: "CITY",
    publicCity: "Brno",
    isDemo: true,
    dataQuality: "stale",
    tags: ["Archiv"],
    media: [],
    priceHistory: [],
    sources: [],
    canonicalKey: "demo:byt-archiv",
  },
  {
    id: "demo-private-owner-b",
    slug: "demo-private-owner-b",
    status: "ACTIVE",
    visibility: "PRIVATE",
    transactionType: "SALE",
    title: "Soukromá nemovitost uživatele B (demo IDOR)",
    description: "Tato položka ověřuje, že User A ji nesmí vidět.",
    propertyType: "APARTMENT",
    askingPrice: 9_999_000,
    currency: "CZK",
    usableArea: 90,
    layout: "4+kk",
    publicLabel: "Skrytá adresa",
    addressPrecision: "EXACT",
    publicCity: "Praha",
    street: "Tajná",
    houseNumber: "1",
    latitude: 50.1,
    longitude: 14.4,
    ownerUserId: "user-b-owner",
    isDemo: true,
    dataQuality: "verified",
    tags: ["Private"],
    internalNotes: "owner B only",
    canonicalKey: "demo:private-b",
    media: [],
    priceHistory: [],
    sources: [],
  },
];

export function getDemoPropertyRecord(slug: string): PropertyRecord | undefined {
  return DEMO_PROPERTY_RECORDS.find((p) => p.slug === slug);
}

export function getDemoPublicProperty(slug: string): PublicPropertyDto | undefined {
  const record = getDemoPropertyRecord(slug);
  if (!record) return undefined;
  if (!canViewProperty(record, { role: "PUBLIC" })) return undefined;
  return toPublicPropertyDto(record);
}

export function listDemoPublicProperties(): PublicPropertyDto[] {
  return DEMO_PROPERTY_RECORDS.filter((r) => canViewProperty(r, { role: "PUBLIC" }))
    .filter((r) => r.status === "ACTIVE")
    .map((r) => toPublicPropertyDto(r));
}
