import type { MarketPlugin } from "@/domains/markets/plugins/types";

export const saMarketPlugin: MarketPlugin = {
  marketCode: "SA",
  definition: {
    marketCode: "SA",
    countryCode: "SA",
    displayNameEn: "Saudi Arabia",
    displayNameLocal: "المملكة العربية السعودية",
    defaultLocale: "ar-SA",
    supportedLocales: ["ar-SA", "en-GB"],
    defaultCurrency: "SAR",
    timezone: "Asia/Riyadh",
    measurementSystem: "METRIC",
    enabled: false,
    launchStatus: "PLANNED",
    regulatoryConfigVersion: "sa-reg.planned",
    hasMinimumPublicData: false,
  },
  property: {
    areaUnit: "sqm",
    supportedPropertyTypes: [
      "APARTMENT",
      "HOUSE",
      "VILLA",
      "LAND",
      "COMMERCIAL",
      "OTHER",
    ],
    addressModel: "GULF",
    titleDeedLabelEn: "Title deed / REGA",
    layoutNotation: "BEDROOM_COUNT",
    detailSectionExtraIds: ["off_plan", "payment_plan"],
    searchFilterExtraKeys: ["bedrooms", "bathrooms", "offPlan", "paymentPlan"],
  },
  transactionCosts: {
    packId: "sa-tx-costs.planned",
    buyerClosingCostBpsEstimate: 500,
    sellerClosingCostBpsEstimate: 250,
    transferTaxLabelEn: "Real estate transaction tax (illustrative)",
    notesEn: "Foreign ownership rules — regulatory pack required.",
  },
  financing: {
    mortgageAvailable: true,
    partnerHandoffEnabled: false,
    typicalLtvMaxPct: 70,
    rateBenchmarkLabelEn: null,
    currency: "SAR",
    primaryProviderCode: null,
  },
  taxation: {
    standardVatRateBp: 1500,
    propertyTaxModel: "TRANSFER_ONLY",
    rentalIncomeTaxNotesEn: "Pending SA regulatory pack.",
    regulatoryPackId: "sa-tax.planned",
    taxPluginId: null,
  },
  regulatory: {
    rulesVersion: "sa-reg.planned",
    renovationCatalogAvailable: false,
    valuationModelCodes: [],
  },
  capabilities: {
    PROPERTY_SEARCH: "NOT_AVAILABLE",
    VALUATION: "NOT_AVAILABLE",
    INVESTMENT_ENGINE: "NOT_AVAILABLE",
    MORTGAGE_CALCULATOR: "NOT_AVAILABLE",
    MORTGAGE_LEAD_HANDOFF: "NOT_AVAILABLE",
    COMPARISON: "NOT_AVAILABLE",
    LOCATION_INTELLIGENCE: "NOT_AVAILABLE",
    LISTING_BOOST: "NOT_AVAILABLE",
    B2B_CRM: "NOT_AVAILABLE",
    QUALIFIED_LEADS: "NOT_AVAILABLE",
    TAX_ESTIMATES: "NOT_AVAILABLE",
    TRANSACTION_COST_ESTIMATES: "NOT_AVAILABLE",
    PROFESSIONAL_SERVICES: "NOT_AVAILABLE",
  },
  featureFlagDefaults: {
    MARKET_SA_VALUATION_ENABLED: false,
  },
};
