import type { MarketPlugin } from "@/domains/markets/plugins/types";

export const esMarketPlugin: MarketPlugin = {
  marketCode: "ES",
  definition: {
    marketCode: "ES",
    countryCode: "ES",
    displayNameEn: "Spain",
    displayNameLocal: "España",
    defaultLocale: "es-ES",
    supportedLocales: ["es-ES", "en-GB"],
    defaultCurrency: "EUR",
    timezone: "Europe/Madrid",
    measurementSystem: "METRIC",
    enabled: false,
    launchStatus: "PLANNED",
    regulatoryConfigVersion: "es-reg.planned",
    hasMinimumPublicData: false,
  },
  property: {
    areaUnit: "sqm",
    supportedPropertyTypes: [
      "APARTMENT",
      "HOUSE",
      "VILLA",
      "LAND",
      "COMMERCIAL",
      "OTHER",
    ],
    addressModel: "EU_STREET",
    titleDeedLabelEn: "Nota simple / Registro de la Propiedad",
    layoutNotation: "BEDROOM_COUNT",
    detailSectionExtraIds: [],
    searchFilterExtraKeys: ["bedrooms", "bathrooms"],
  },
  transactionCosts: {
    packId: "es-tx-costs.planned",
    buyerClosingCostBpsEstimate: 1000,
    sellerClosingCostBpsEstimate: 500,
    transferTaxLabelEn: "ITP / VAT / AJD (illustrative)",
    notesEn: "High closing-cost market — pack required before LIVE.",
  },
  financing: {
    mortgageAvailable: true,
    partnerHandoffEnabled: false,
    typicalLtvMaxPct: 80,
    rateBenchmarkLabelEn: null,
    currency: "EUR",
    primaryProviderCode: null,
  },
  taxation: {
    standardVatRateBp: 2100,
    propertyTaxModel: "MIXED",
    rentalIncomeTaxNotesEn: "IRPF / non-resident rules — pending pack.",
    regulatoryPackId: "es-tax.planned",
    taxPluginId: null,
  },
  regulatory: {
    rulesVersion: "es-reg.planned",
    renovationCatalogAvailable: false,
    valuationModelCodes: [],
  },
  capabilities: {
    PROPERTY_SEARCH: "LIMITED",
    VALUATION: "NOT_AVAILABLE",
    INVESTMENT_ENGINE: "NOT_AVAILABLE",
    MORTGAGE_CALCULATOR: "NOT_AVAILABLE",
    MORTGAGE_LEAD_HANDOFF: "NOT_AVAILABLE",
    COMPARISON: "LIMITED",
    LOCATION_INTELLIGENCE: "NOT_AVAILABLE",
    LISTING_BOOST: "NOT_AVAILABLE",
    B2B_CRM: "NOT_AVAILABLE",
    QUALIFIED_LEADS: "NOT_AVAILABLE",
    TAX_ESTIMATES: "NOT_AVAILABLE",
    TRANSACTION_COST_ESTIMATES: "LIMITED",
    PROFESSIONAL_SERVICES: "NOT_AVAILABLE",
  },
  featureFlagDefaults: {
    MARKET_ES_VALUATION_ENABLED: false,
  },
};
